name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/AspNetCore.Identity.Mongo/
    - name: Build
      run: dotnet build ./src/AspNetCore.Identity.Mongo/ -c Release --no-restore
    - name: Test
      run: dotnet test ./Tests -c Release
